#!/bin/sh

VERSION=1.0

#####################################################################

IMAGE=`mktemp`
CHROOT=`mktemp -d`

echo ">> Installing helper tools..."
export DEBIAN_FRONTEND=noninteractive
apt-get -q -y update
apt-get -q -y install debootstrap qemu-utils kpartx virtualbox

echo ">> Creating disk image file..."
qemu-img create -fraw $IMAGE 20G

echo ">> Partitioning image file..."
losetup /dev/loop0 $IMAGE
echo "n
p
1

+19G
n
p
2


t
2
82
w
" | fdisk /dev/loop0
kpartx -a /dev/loop0

echo ">> Creating filesystem..."
losetup /dev/loop1 /dev/mapper/loop0p1
losetup /dev/loop2 /dev/mapper/loop0p2
mkfs.ext3 -j /dev/loop1
mkswap /dev/loop2

echo ">> Mounting filesystem..."
mount /dev/loop1 $CHROOT

echo ">> Bootstrapping template..."
debootstrap --exclude=nano --include=ssh,less,wget,vim,sudo precise $CHROOT http://nl.archive.ubuntu.com/ubuntu/

echo ">> Mounting /dev in chroot environment..."
mount --bind /dev $CHROOT/dev

echo ">> Setup image..."
cp /vagrant/debs/xe-guest-utilities_6.0.2-762_amd64.deb $CHROOT/root
cp /vagrant/scripts/setup-template $CHROOT
chroot $CHROOT /setup-template

echo ">> Configuring cloud-init..."
cp /vagrant/tmp/cloud.cfg $CHROOT/etc/cloud.cfg
rm -f $CHROOT/etc/cloud/cloud.cfg.d/90_dpkg.cfg

echo ">> Cleaning up..."
umount $CHROOT/dev
umount $CHROOT
losetup -d /dev/loop2
losetup -d /dev/loop1
kpartx -d /dev/loop0
losetup -d /dev/loop0

echo ">> Converting image to VHD format..."
rm -f /vagrant/vdt-base-$VERSION.vhd
VBoxManage -q convertfromraw $IMAGE /vagrant/vdt-base-$VERSION.vhd --format VHD

echo ">> Image ready!"
