#!/bin/sh
export DEBIAN_FRONTEND=noninteractive
mount -t proc none /proc
mount -t sysfs none /sys

echo ">> Setting locale..."
cat >> /etc/environment << EOF
LANGUAGE=en_US.UTF-8
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
EOF
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
locale-gen en_US.UTF-8
dpkg-reconfigure locales

echo ">> Installing kernel..."
apt-get -q -y install linux-image grub-pc cloud-init

VERSION=`ls /boot/vmlinuz-*|tail -1|sed 's/.*vmlinuz-//'`
UUIDROOT=`blkid -o value -s UUID /dev/loop1`
UUIDSWAP=`blkid -o value -s UUID /dev/loop2`

echo ">> Creating fstab..."
cat > /etc/fstab << EOF
proc		/proc		proc		nodev,noexec,nosuid		0 0
UUID=$UUIDROOT	/		ext3		errors=remount-ro,barrier=0	1 2
UUID=$UUIDSWAP	none		swap		sw				0 0
EOF

echo ">> Setup networking..."
cat > /etc/network/interfaces << EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
EOF

echo ">> Installing GRUB bootloader..."
mkdir -p /boot/grub
cat > /boot/grub/device.map << EOF
(hd0) /dev/loop0
(hd0,1) /dev/loop1
EOF

cat > /boot/grub/grub.cfg << EOF
set default="0"
set timeout=5
menuentry 'Ubuntu, with Linux $VERSION' --class ubuntu --class gnu-linux --class gnu --class os {
	insmod gzio
	insmod part_msdos
	insmod ext2
	set root='(hd0,1)'
	search --no-floppy --fs-uuid --set=root $UUIDROOT
	linux	/boot/vmlinuz-$VERSION root=UUID=$UUIDROOT ro quiet
	initrd	/boot/initrd.img-$VERSION
}
EOF
grub-install --no-floppy --grub-mkdevicemap=/boot/grub/device.map /dev/loop0

echo ">> Setting root password..."
echo "root:avira" | chpasswd

echo ">> Install XEN tools..."
dpkg -i /root/xe-guest-utilities_6.0.2-762_amd64.deb

echo ">> Configuring Puppet repo..."
cd /tmp
wget -O /tmp/puppetlabs-release-precise.deb http://apt.puppetlabs.com/puppetlabs-release-precise.deb
dpkg -i /tmp/puppetlabs-release-precise.deb

cat > /etc/apt/preferences.d/pin-puppet << EOF
Package: puppet-common
Pin: version 2.7.19-1puppetlabs2
Pin-Priority: 1001

Package: puppet
Pin: version 2.7.19-1puppetlabs2
Pin-Priority: 1001

Package: puppetmaster-common
Pin: version 2.7.19-1puppetlabs2
Pin-Priority: 1001

Package: puppetmaster
Pin: version 2.7.19-1puppetlabs2
Pin-Priority: 1001

Package: puppetmaster-passenger
Pin: version 2.7.19-1puppetlabs2
Pin-Priority: 1001
EOF
apt-get -q -y update

echo ">> Cleanup..."
apt-get -q -y clean
apt-get -q -y autoremove

umount /sys
umount /proc
